// ignore_for_file: depend_on_referenced_packages

import 'package:codifyiq_firebase_authentication/codifyiq_firebase_authentication.dart';
import 'package:firebase_core/firebase_core.dart';

/// Example showing how to initialize Firebase authentication and sign in.
///
/// Replace the [FirebaseOptions] below with your own values generated by
/// `flutterfire configure`.
Future<void> main() async {
  // 1. Initialize Firebase with your project's options.
  await FirebaseAuthInitializer.initialize(
    firebaseOptions: const FirebaseOptions(
      apiKey: 'your-api-key',
      appId: 'your-app-id',
      messagingSenderId: 'your-sender-id',
      projectId: 'your-project-id',
    ),
  );

  // 2. Create the auth service.
  final authService = FirebaseAuthService();

  // 3. Sign in with Google and handle the result.
  final result = await authService.signInWithGoogle();
  switch (result) {
    case FirebaseAuthSuccess(:final credential):
      print('Signed in as ${credential.user?.email}');
    case FirebaseAuthFailure(:final message):
      print('Sign-in failed: $message');
    case FirebaseAuthCancelled():
      print('Sign-in cancelled');
  }

  // 4. Sign out.
  await authService.signOut();
}
